# -*- coding: utf-8 -*-

#    This script is based on the one of script.xbmc.subtitles
#    Thanks to their original authors amet, mr_blobby

LANGUAGES      = (

    # Full Language name[0]     podnapisi[1]  ISO 639-1[2]   ISO 639-2 Code(s)[3]   Script Setting Language[4]   localized name id number[5]

    ("Albanian"                   , "29",       "sq",            "alb",                 "0",                     30201  ),
    ("Arabic"                     , "12",       "ar",            "ara",                 "1",                     30202  ),
    ("Belarusian"                 , "0" ,       "be",            "bel",                 "2",                     30203  ),
    ("Bosnian"                    , "10",       "bs",            "bos",                 "3",                     30204  ),
    ("Bulgarian"                  , "33",       "bg",            "bul",                 "4",                     30205  ),
    ("Catalan"                    , "53",       "ca",            "cat",                 "5",                     30206  ),
    ("Chinese"                    , "17",       "zh",            "chi",                 "6",                     30207  ),
    ("Croatian"                   , "38",       "hr",            "hrv",                 "7",                     30208  ),
    ("Czech"                      , "7",        "cs",            "cze",                 "8",                     30209  ),
    ("Danish"                     , "24",       "da",            "dan",                 "9",                     30210  ),
    ("Dutch"                      , "23",       "nl",            "dut",                 "10",                    30211  ),
    ("English"                    , "2",        "en",            "eng",                 "11",                    30212  ),
    ("Estonian"                   , "20",       "et",            "est",                 "12",                    30213  ),
    ("Farsi"                      , "52",       "fa",            "per",                 "13",                    30214  ),
    ("Finnish"                    , "31",       "fi",            "fin",                 "14",                    30215  ),
    ("French"                     , "8",        "fr",            "fre",                 "15",                    30216  ),
    ("German"                     , "5",        "de",            "ger,deu",             "16",                    30217  ),
    ("Greek"                      , "16",       "el",            "ell,gre",             "17",                    30218  ),
    ("Hebrew"                     , "22",       "he",            "heb",                 "18",                    30219  ),
    ("Hindi"                      , "42",       "hi",            "hin",                 "19",                    30220  ),
    ("Hungarian"                  , "15",       "hu",            "hun",                 "20",                    30221  ),
    ("Icelandic"                  , "6",        "is",            "ice",                 "21",                    30222  ),
    ("Indonesian"                 , "0",        "id",            "ind",                 "22",                    30223  ),
    ("Italian"                    , "9",        "it",            "ita",                 "23",                    30224  ),
    ("Japanese"                   , "11",       "ja",            "jpn",                 "24",                    30225  ),
    ("Korean"                     , "4",        "ko",            "kor",                 "25",                    30226  ),
    ("Latvian"                    , "21",       "lv",            "lav",                 "26",                    30227  ),
    ("Lithuanian"                 , "0",        "lt",            "lit",                 "27",                    30228  ),
    ("Macedonian"                 , "35",       "mk",            "mac",                 "28",                    30229  ),
    ("Norwegian"                  , "3",        "no",            "nor",                 "29",                    30230  ),
    ("Persian"                    , "52",       "fa",            "per",                 "30",                    30231  ),
    ("Polish"                     , "26",       "pl",            "pol",                 "31",                    30232  ),
    ("Portuguese"                 , "32",       "pt",            "por",                 "32",                    30233  ),
    ("Portuguese (Brazil)"        , "48",       "pb",            "pob,pt-br",               "33",                    30234  ),
    ("Romanian"                   , "13",       "ro",            "rum",                 "34",                    30235  ),
    ("Russian"                    , "27",       "ru",            "rus",                 "35",                    30236  ),
    ("Serbian"                    , "36",       "sr",            "srp,scc",             "36",                    30237  ),
    ("Slovak"                     , "37",       "sk",            "slo",                 "37",                    30238  ),
    ("Slovenian"                  , "1",        "sl",            "slv",                 "38",                    30239  ),
    ("Spanish"                    , "28",       "es",            "spa",                 "39",                    30240  ),
    ("Swedish"                    , "25",       "sv",            "swe",                 "40",                    30241  ),
    ("Thai"                       , "0",        "th",            "tha",                 "41",                    30242  ),
    ("Turkish"                    , "30",       "tr",            "tur",                 "42",                    30243  ),
    ("Ukrainian"                  , "46",       "uk",            "ukr",                 "43",                    30244  ),
    ("Vietnamese"                 , "51",       "vi",            "vie",                 "44",                    30245  ),
    ("English Middle"             , "2",        "",              "enm",                 "47",                    30248  ),
    ("Norwegian Bokmal"           , "3",        "nb",            "nob",                 "48",                    30249  ),
    ("New Norwegian"              , "3",        "nn",            "nno",                 "49",                    30250  ),
    ("English (UK)"                , "0",      "en",            "en-GB",                "53",                    30251   ),
    ("English (US)"                , "0",      "en",            "en-US",                "54",                    30252   ),
    ("English (Australia)"         , "0",      "en",            "en-AU",                "55",                    30253   ),
    ("Spanish (Spain)"             , "0",      "es",            "es-ES",                "56",                    30254   ),
    ("Spanish (Latin America)"     , "0",      "es",            "es-419",               "57",                    30255   ),
    ("French (Canada)"             , "0",      "fr",            "fr-CA",                "58",                    30256   ),
    ("Portuguese (Portugal)"       , "0",      "pt",            "pt-PT",                "59",                    30257   ),
    ("Chinese (Simplified)"        , "0",      "zh",            "zh-Hans",              "60",                    30258   ),
    ("Chinese (Traditional)"       , "0",      "zh",            "zh-Hant",              "61",                    30259   ),
    ("English (India)"             , "0",      "en",            "en-IN",                "62",                    30260   ),
    ("English (Canada)"            , "0",      "en",            "en-CA",                "63",                    30261   ),
    ("German (Switzerland)"        , "0",      "de",            "de-CH",                "64",                    30262   ),
    ("German (Austria)"            , "0",      "de",            "de-AT",                "65",                    30263   ),
    ("French (Belgium)"            , "0",      "fr",            "fr-BE",                "66",                    30264   ),
    ("French (Switzerland)"        , "0",      "fr",            "fr-CH",                "67",                    30265   ),
    ("Dutch (Belgium)"             , "0",      "nl",            "nl-BE",                "68",                    30266   ),
    ("None"                       , "-1",       "",              "non",                 "45",                    30200  ),
    ("Any"                        , "-2",       "",              "any",                 "46",                    30300  ),
    ("Undefined"                  , "-3",       "",              "und",                 "50",                    30350  ),
    ("Unknown"                  , "-4",       "",              "unk",                 "51",                    30400  ),
    ("Original"                  , "-5",       "",              "org",                 "52",                    30500  ))


# ---------------------------------------------------------------------------------------------
# Language lookup tables used by langutils.py (matching works for ANY language below, not only the
# ones offered in the settings spinner).
#
# ISO639_1_TO_2B : ISO 639-1 (2 letters) -> ISO 639-2/B (3 letters). Generated from Kodi's own table
#                  (xbmc/language/i18n/TableLanguageCodes.h, Kodi master / Piers).  Do not edit by hand.
# ISO639_2T_TO_2B: ISO 639-2/T (terminology) -> /B (bibliographic) codes that differ (deu->ger, fra->fre ...), from Kodi
# LEGACY_TO_2B   : retired / non-standard 3 letter codes still found in files
# LANGUAGE_NAMES : ISO 639-2/B -> English name (Kodi's Iso639_1_Table.h / Iso639_2_Table.h)
# NAME_TO_2B     : lower-case single-word English language name -> ISO 639-2/B (used to read a language
#                  from a track title when the stream carries no usable language tag)
# ---------------------------------------------------------------------------------------------
ISO639_1_TO_2B = {
    'aa': 'aar', 'ab': 'abk', 'ae': 'ave', 'af': 'afr', 'ak': 'aka', 'am': 'amh',
    'an': 'arg', 'ar': 'ara', 'as': 'asm', 'av': 'ava', 'ay': 'aym', 'az': 'aze',
    'ba': 'bak', 'be': 'bel', 'bg': 'bul', 'bh': 'bih', 'bi': 'bis', 'bm': 'bam',
    'bn': 'ben', 'bo': 'tib', 'br': 'bre', 'bs': 'bos', 'ca': 'cat', 'ce': 'che',
    'ch': 'cha', 'co': 'cos', 'cr': 'cre', 'cs': 'cze', 'cu': 'chu', 'cv': 'chv',
    'cy': 'wel', 'da': 'dan', 'de': 'ger', 'dv': 'div', 'dz': 'dzo', 'ee': 'ewe',
    'el': 'gre', 'en': 'eng', 'eo': 'epo', 'es': 'spa', 'et': 'est', 'eu': 'baq',
    'fa': 'per', 'ff': 'ful', 'fi': 'fin', 'fj': 'fij', 'fo': 'fao', 'fr': 'fre',
    'fy': 'fry', 'ga': 'gle', 'gd': 'gla', 'gl': 'glg', 'gn': 'grn', 'gu': 'guj',
    'gv': 'glv', 'ha': 'hau', 'he': 'heb', 'hi': 'hin', 'ho': 'hmo', 'hr': 'hrv',
    'ht': 'hat', 'hu': 'hun', 'hy': 'arm', 'hz': 'her', 'ia': 'ina', 'id': 'ind',
    'ie': 'ile', 'ig': 'ibo', 'ii': 'iii', 'ik': 'ipk', 'in': 'ind', 'io': 'ido',
    'is': 'ice', 'it': 'ita', 'iu': 'iku', 'iw': 'heb', 'ja': 'jpn', 'ji': 'yid',
    'jv': 'jav', 'jw': 'jav', 'ka': 'geo', 'kg': 'kon', 'ki': 'kik', 'kj': 'kua',
    'kk': 'kaz', 'kl': 'kal', 'km': 'khm', 'kn': 'kan', 'ko': 'kor', 'kr': 'kau',
    'ks': 'kas', 'ku': 'kur', 'kv': 'kom', 'kw': 'cor', 'ky': 'kir', 'la': 'lat',
    'lb': 'ltz', 'lg': 'lug', 'li': 'lim', 'ln': 'lin', 'lo': 'lao', 'lt': 'lit',
    'lu': 'lub', 'lv': 'lav', 'mg': 'mlg', 'mh': 'mah', 'mi': 'mao', 'mk': 'mac',
    'ml': 'mal', 'mn': 'mon', 'mo': 'rum', 'mr': 'mar', 'ms': 'may', 'mt': 'mlt',
    'my': 'bur', 'na': 'nau', 'nb': 'nob', 'nd': 'nde', 'ne': 'nep', 'ng': 'ndo',
    'nl': 'dut', 'nn': 'nno', 'no': 'nor', 'nr': 'nbl', 'nv': 'nav', 'ny': 'nya',
    'oc': 'oci', 'oj': 'oji', 'om': 'orm', 'or': 'ori', 'os': 'oss', 'pa': 'pan',
    'pb': 'pob', 'pi': 'pli', 'pl': 'pol', 'ps': 'pus', 'pt': 'por', 'qu': 'que',
    'rm': 'roh', 'rn': 'run', 'ro': 'rum', 'ru': 'rus', 'rw': 'kin', 'sa': 'san',
    'sc': 'srd', 'sd': 'snd', 'se': 'sme', 'sg': 'sag', 'sh': 'scr', 'si': 'sin',
    'sk': 'slo', 'sl': 'slv', 'sm': 'smo', 'sn': 'sna', 'so': 'som', 'sq': 'alb',
    'sr': 'srp', 'ss': 'ssw', 'st': 'sot', 'su': 'sun', 'sv': 'swe', 'sw': 'swa',
    'ta': 'tam', 'te': 'tel', 'tg': 'tgk', 'th': 'tha', 'ti': 'tir', 'tk': 'tuk',
    'tl': 'tgl', 'tn': 'tsn', 'to': 'ton', 'tr': 'tur', 'ts': 'tso', 'tt': 'tat',
    'tw': 'twi', 'ty': 'tah', 'ug': 'uig', 'uk': 'ukr', 'ur': 'urd', 'uz': 'uzb',
    've': 'ven', 'vi': 'vie', 'vo': 'vol', 'wa': 'wln', 'wo': 'wol', 'xh': 'xho',
    'yi': 'yid', 'yo': 'yor', 'za': 'zha', 'zh': 'chi', 'zu': 'zul',
}

ISO639_2T_TO_2B = {
    'bod': 'tib', 'ces': 'cze', 'cym': 'wel', 'deu': 'ger', 'ell': 'gre',
    'eus': 'baq', 'fas': 'per', 'fra': 'fre', 'hye': 'arm', 'isl': 'ice',
    'kat': 'geo', 'mkd': 'mac', 'mri': 'mao', 'msa': 'may', 'mya': 'bur',
    'nld': 'dut', 'ron': 'rum', 'slk': 'slo', 'sqi': 'alb', 'zho': 'chi',
}

LEGACY_TO_2B = {
    'scc': 'srp', 'scr': 'hrv',
}

LANGUAGE_NAMES = {
    'aar': 'Afar', 'abk': 'Abkhazian', 'ace': 'Achinese',
    'ach': 'Acoli', 'ada': 'Adangme', 'ady': 'Adyghe',
    'afa': 'Afro-Asiatic languages', 'afh': 'Afrihili', 'afr': 'Afrikaans',
    'ain': 'Ainu', 'aka': 'Akan', 'akk': 'Akkadian',
    'alb': 'Albanian', 'ale': 'Aleut', 'alg': 'Algonquian languages',
    'alt': 'Southern Altai', 'amh': 'Amharic', 'ang': 'English, Old (ca.450–1100)',
    'anp': 'Angika', 'apa': 'Apache languages', 'ara': 'Arabic',
    'arc': 'Official Aramaic (700–300 BCE)', 'arg': 'Aragonese', 'arm': 'Armenian',
    'arn': 'Mapudungun', 'arp': 'Arapaho', 'art': 'Artificial languages',
    'arw': 'Arawak', 'asm': 'Assamese', 'ast': 'Asturian',
    'ath': 'Athapascan languages', 'aus': 'Australian languages', 'ava': 'Avaric',
    'ave': 'Avestan', 'awa': 'Awadhi', 'aym': 'Aymara',
    'aze': 'Azerbaijani', 'bad': 'Banda languages', 'bai': 'Bamileke languages',
    'bak': 'Bashkir', 'bal': 'Baluchi', 'bam': 'Bambara',
    'ban': 'Balinese', 'baq': 'Basque', 'bas': 'Basa',
    'bat': 'Baltic languages', 'bej': 'Beja', 'bel': 'Belarusian',
    'bem': 'Bemba', 'ben': 'Bengali', 'ber': 'Berber languages',
    'bho': 'Bhojpuri', 'bih': 'Bihari', 'bik': 'Bikol',
    'bin': 'Bini', 'bis': 'Bislama', 'bla': 'Siksika',
    'bnt': 'Bantu languages', 'bos': 'Bosnian', 'bra': 'Braj',
    'bre': 'Breton', 'btk': 'Batak languages', 'bua': 'Buriat',
    'bug': 'Buginese', 'bul': 'Bulgarian', 'bur': 'Burmese',
    'byn': 'Blin', 'cad': 'Caddo', 'cai': 'Central American Indian languages',
    'car': 'Galibi Carib', 'cat': 'Catalan', 'cau': 'Caucasian languages',
    'ceb': 'Cebuano', 'cel': 'Celtic languages', 'cha': 'Chamorro',
    'chb': 'Chibcha', 'che': 'Chechen', 'chg': 'Chagatai',
    'chi': 'Chinese', 'chk': 'Chuukese', 'chm': 'Mari',
    'chn': 'Chinook Jargon', 'cho': 'Choctaw', 'chp': 'Chipewyan',
    'chr': 'Cherokee', 'chu': 'Church Slavic', 'chv': 'Chuvash',
    'chy': 'Cheyenne', 'cmc': 'Chamic languages', 'cnr': 'Montenegrin',
    'cop': 'Coptic', 'cor': 'Cornish', 'cos': 'Corsican',
    'cpe': 'Creoles and pidgins, English based', 'cpf': 'Creoles and pidgins, French-based', 'cpp': 'Creoles and pidgins, Portuguese-based',
    'cre': 'Cree', 'crh': 'Crimean Tatar', 'crp': 'Creoles and pidgins',
    'csb': 'Kashubian', 'cus': 'Cushitic languages', 'cze': 'Czech',
    'dak': 'Dakota', 'dan': 'Danish', 'dar': 'Dargwa',
    'day': 'Land Dayak languages', 'del': 'Delaware', 'den': 'Slave (Athapascan)',
    'dgr': 'Tlicho', 'din': 'Dinka', 'div': 'Dhivehi',
    'doi': 'Dogri', 'dra': 'Dravidian languages', 'dsb': 'Lower Sorbian',
    'dua': 'Duala', 'dum': 'Dutch, Middle (ca. 1050–1350)', 'dut': 'Dutch',
    'dyu': 'Dyula', 'dzo': 'Dzongkha', 'efi': 'Efik',
    'egy': 'Egyptian (Ancient)', 'eka': 'Ekajuk', 'elx': 'Elamite',
    'eng': 'English', 'enm': 'English, Middle (1100–1500)', 'epo': 'Esperanto',
    'est': 'Estonian', 'ewe': 'Ewe', 'ewo': 'Ewondo',
    'fan': 'Fang', 'fao': 'Faroese', 'fat': 'Fanti',
    'fij': 'Fijian', 'fil': 'Filipino', 'fin': 'Finnish',
    'fiu': 'Finno-Ugrian languages', 'fon': 'Fon', 'fre': 'French',
    'frm': 'French, Middle (ca. 1400–1600)', 'fro': 'French, Old (842–ca. 1400)', 'frr': 'Northern Frisian',
    'frs': 'Eastern Frisian', 'fry': 'Western Frisian', 'ful': 'Fulah',
    'fur': 'Friulian', 'gaa': 'Ga', 'gay': 'Gayo',
    'gba': 'Gbaya', 'gem': 'Germanic languages', 'geo': 'Georgian',
    'ger': 'German', 'gez': 'Geez', 'gil': 'Gilbertese',
    'gla': 'Scottish Gaelic', 'gle': 'Irish', 'glg': 'Galician',
    'glv': 'Manx', 'gmh': 'German, Middle High (ca. 1050–1500)', 'goh': 'German, Old High (ca. 750–1050)',
    'gon': 'Gondi', 'gor': 'Gorontalo', 'got': 'Gothic',
    'grb': 'Grebo', 'grc': 'Greek, Ancient (to 1453)', 'gre': 'Greek',
    'grn': 'Guarani', 'gsw': 'Swiss German', 'guj': 'Gujarati',
    'gwi': "Gwich'in", 'hai': 'Haida', 'hat': 'Haitian',
    'hau': 'Hausa', 'haw': 'Hawaiian', 'heb': 'Hebrew',
    'her': 'Herero', 'hil': 'Hiligaynon', 'him': 'Himachali\xa0languages',
    'hin': 'Hindi', 'hit': 'Hittite', 'hmn': 'Hmong',
    'hmo': 'Hiri Motu', 'hrv': 'Croatian', 'hsb': 'Upper Sorbian',
    'hun': 'Hungarian', 'hup': 'Hupa', 'iba': 'Iban',
    'ibo': 'Igbo', 'ice': 'Icelandic', 'ido': 'Ido',
    'iii': 'Sichuan Yi', 'ijo': 'Ijo languages', 'iku': 'Inuktitut',
    'ile': 'Interlingue', 'ilo': 'Iloko', 'ina': 'Interlingua',
    'inc': 'Indic languages', 'ind': 'Indonesian', 'ine': 'Indo-European languages',
    'inh': 'Ingush', 'ipk': 'Inupiat', 'ira': 'Iranian languages',
    'iro': 'Iroquoian languages', 'ita': 'Italian', 'jav': 'Javanese',
    'jbo': 'Lojban', 'jpn': 'Japanese', 'jpr': 'Judeo-Persian',
    'jrb': 'Judeo-Arabic', 'kaa': 'Kara-Kalpak', 'kab': 'Kabyle',
    'kac': 'Kachin', 'kal': 'Kalaallisut', 'kam': 'Kamba',
    'kan': 'Kannada', 'kar': 'Karen languages', 'kas': 'Kashmiri',
    'kau': 'Kanuri', 'kaw': 'Kawi', 'kaz': 'Kazakh',
    'kbd': 'Kabardian', 'kha': 'Khasi', 'khi': 'Khoisan languages',
    'khm': 'Khmer', 'kho': 'Khotanese', 'kik': 'Kikuyu',
    'kin': 'Kinyarwanda', 'kir': 'Kirghiz', 'kmb': 'Kimbundu',
    'kok': 'Konkani', 'kom': 'Komi', 'kon': 'Kongo',
    'kor': 'Korean', 'kos': 'Kosraean', 'kpe': 'Kpelle',
    'krc': 'Karachay-Balkar', 'krl': 'Karelian', 'kro': 'Kru languages',
    'kru': 'Kurukh', 'kua': 'Kuanyama', 'kum': 'Kumyk',
    'kur': 'Kurdish', 'kut': 'Kutenai', 'lad': 'Ladino',
    'lah': 'Lahnda', 'lam': 'Lamba', 'lao': 'Lao',
    'lat': 'Latin', 'lav': 'Latvian, Lettish', 'lez': 'Lezghian',
    'lim': 'Limburgan', 'lin': 'Lingala', 'lit': 'Lithuanian',
    'lol': 'Mongo', 'loz': 'Lozi', 'ltz': 'Luxembourgish',
    'lua': 'Luba-Lulua', 'lub': 'Luba-Katanga', 'lug': 'Ganda',
    'lui': 'Luiseno', 'lun': 'Lunda', 'luo': 'Luo (Kenya and Tanzania)',
    'lus': 'Lushai', 'mac': 'Macedonian', 'mad': 'Madurese',
    'mag': 'Magahi', 'mah': 'Marshallese', 'mai': 'Maithili',
    'mak': 'Makasar', 'mal': 'Malayalam', 'man': 'Mandingo',
    'mao': 'Maori', 'map': 'Austronesian languages', 'mar': 'Marathi',
    'mas': 'Masai', 'may': 'Malay', 'mdf': 'Moksha',
    'mdr': 'Mandar', 'men': 'Mende', 'mga': 'Irish, Middle (900–1200)',
    'mic': "Mi'kmaq", 'min': 'Minangkabau', 'mis': 'Uncoded languages',
    'mkh': 'Mon-Khmer languages', 'mlg': 'Malagasy', 'mlt': 'Maltese',
    'mnc': 'Manchu', 'mni': 'Manipuri', 'mno': 'Manobo languages',
    'moh': 'Mohawk', 'mon': 'Mongolian', 'mos': 'Mossi',
    'mul': 'Multiple languages', 'mun': 'Munda languages', 'mus': 'Creek',
    'mwl': 'Mirandese', 'mwr': 'Marwari', 'myn': 'Mayan languages',
    'myv': 'Erzya', 'nah': 'Nahuatl languages', 'nai': 'North American Indian languages',
    'nap': 'Neapolitan', 'nau': 'Nauru', 'nav': 'Navajo',
    'nbl': 'Ndebele, South', 'nde': 'Ndebele, North', 'ndo': 'Ndonga',
    'nds': 'Low German', 'nep': 'Nepali', 'new': 'Nepal Bhasa',
    'nia': 'Nias', 'nic': 'Niger-Kordofanian languages', 'niu': 'Niuean',
    'nno': 'Norwegian Nynorsk', 'nob': 'Norwegian Bokmål', 'nog': 'Nogai',
    'non': 'Norse, Old', 'nor': 'Norwegian', 'nqo': "N'Ko",
    'nso': 'Pedi', 'nub': 'Nubian languages', 'nwc': 'Classical\xa0Newari',
    'nya': 'Chichewa', 'nym': 'Nyamwezi', 'nyn': 'Nyankole',
    'nyo': 'Nyoro', 'nzi': 'Nzima', 'oci': 'Occitan',
    'oji': 'Ojibwa', 'ori': 'Oriya', 'orm': 'Oromo',
    'osa': 'Osage', 'oss': 'Ossetic', 'ota': 'Turkish, Ottoman (1500–1928)',
    'oto': 'Otomian languages', 'paa': 'Papuan languages', 'pag': 'Pangasinan',
    'pal': 'Pahlavi', 'pam': 'Pampanga', 'pan': 'Punjabi',
    'pap': 'Papiamento', 'pau': 'Palauan', 'peo': 'Persian, Old (c.\u2009600–400 B.C.)',
    'per': 'Persian', 'phi': 'Philippine languages', 'phn': 'Phoenician',
    'pli': 'Pali', 'pob': 'Portuguese (Brazil)', 'pol': 'Polish',
    'pon': 'Pohnpeian', 'por': 'Portuguese', 'pra': 'Prakrit languages',
    'pro': 'Provençal, Old (to 1500)', 'pus': 'Pashto, Pushto', 'que': 'Quechua',
    'raj': 'Rajasthani', 'rap': 'Rapanui', 'rar': 'Rarotongan',
    'roa': 'Romance languages', 'roh': 'Romansh', 'rom': 'Romany',
    'rum': 'Romanian', 'run': 'Kirundi', 'rup': 'Aromanian',
    'rus': 'Russian', 'sad': 'Sandawe', 'sag': 'Sangho',
    'sah': 'Yakut', 'sai': 'South American Indian languages', 'sal': 'Salishan languages',
    'sam': 'Samaritan Aramaic', 'san': 'Sanskrit', 'sas': 'Sasak',
    'sat': 'Santali', 'scn': 'Sicilian', 'sco': 'Scots',
    'scr': 'Serbo-Croatian', 'sel': 'Selkup', 'sem': 'Semitic languages',
    'sga': 'Irish, Old (to 900)', 'sgn': 'Sign languages', 'shn': 'Shan',
    'sid': 'Sidamo', 'sin': 'Sinhalese', 'sio': 'Siouan languages',
    'sit': 'Sino-Tibetan languages', 'sla': 'Slavic languages', 'slo': 'Slovak',
    'slv': 'Slovenian', 'sma': 'Southern Sami', 'sme': 'Northern Sami',
    'smi': 'Sami languages', 'smj': 'Lule Sami', 'smn': 'Inari Sami',
    'smo': 'Samoan', 'sms': 'Skolt Sami', 'sna': 'Shona',
    'snd': 'Sindhi', 'snk': 'Soninke', 'sog': 'Sogdian',
    'som': 'Somali', 'son': 'Songhai languages', 'sot': 'Sesotho',
    'spa': 'Spanish', 'srd': 'Sardinian', 'srn': 'Sranan Tongo',
    'srp': 'Serbian', 'srr': 'Serer', 'ssa': 'Nilo-Saharan languages',
    'ssw': 'Swati', 'suk': 'Sukuma', 'sun': 'Sundanese',
    'sus': 'Susu', 'sux': 'Sumerian', 'swa': 'Swahili',
    'swe': 'Swedish', 'syc': 'Classical Syriac', 'syr': 'Syriac',
    'tah': 'Tahitian', 'tai': 'Tai languages', 'tam': 'Tamil',
    'tat': 'Tatar', 'tel': 'Telugu', 'tem': 'Timne',
    'ter': 'Tereno', 'tet': 'Tetum', 'tgk': 'Tajik',
    'tgl': 'Tagalog', 'tha': 'Thai', 'tib': 'Tibetan',
    'tig': 'Tigre', 'tir': 'Tigrinya', 'tiv': 'Tiv',
    'tkl': 'Tokelau', 'tlh': 'Klingon', 'tli': 'Tlingit',
    'tmh': 'Tamashek', 'tog': 'Tonga (Nyasa)', 'ton': 'Tonga',
    'tpi': 'Tok Pisin', 'tsi': 'Tsimshian', 'tsn': 'Tswana',
    'tso': 'Tsonga', 'tuk': 'Turkmen', 'tum': 'Tumbuka',
    'tup': 'Tupi languages', 'tur': 'Turkish', 'tut': 'Altaic languages',
    'tvl': 'Tuvalu', 'twi': 'Twi', 'tyv': 'Tuvinian',
    'udm': 'Udmurt', 'uga': 'Ugaritic', 'uig': 'Uighur',
    'ukr': 'Ukrainian', 'umb': 'Umbundu', 'und': 'Undetermined',
    'urd': 'Urdu', 'uzb': 'Uzbek', 'vai': 'Vai',
    'ven': 'Venda', 'vie': 'Vietnamese', 'vol': 'Volapuk',
    'vot': 'Votic', 'wak': 'Wakashan languages', 'wal': 'Wolaitta',
    'war': 'Waray', 'was': 'Washo', 'wel': 'Welsh',
    'wen': 'Sorbian languages', 'wln': 'Walloon', 'wol': 'Wolof',
    'xal': 'Kalmyk', 'xho': 'Xhosa', 'yao': 'Yao',
    'yap': 'Yapese', 'yid': 'Yiddish', 'yor': 'Yoruba',
    'ypk': 'Yupik languages', 'zap': 'Zapotec', 'zbl': 'Blissymbols',
    'zen': 'Zenaga', 'zgh': 'Standard Moroccan Tamazight', 'zha': 'Zhuang',
    'znd': 'Zande languages', 'zul': 'Zulu', 'zun': 'Zuni',
    'zxx': 'No linguistic content', 'zza': 'Zaza',
}

NAME_TO_2B = {
    'abkhaz': 'abk', 'abkhazian': 'abk', 'achinese': 'ace', 'acoli': 'ach',
    'adangme': 'ada', 'adygei': 'ady', 'adyghe': 'ady', 'afar': 'aar',
    'afrihili': 'afh', 'afrikaans': 'afr', 'ainu': 'ain', 'akan': 'aka',
    'akkadian': 'akk', 'albanian': 'alb', 'alemannic': 'gsw', 'aleut': 'ale',
    'alsatian': 'gsw', 'amharic': 'amh', 'angika': 'anp', 'arabic': 'ara',
    'aragonese': 'arg', 'arapaho': 'arp', 'arawak': 'arw', 'armenian': 'arm',
    'aromanian': 'rup', 'arumanian': 'rup', 'assamese': 'asm', 'asturian': 'ast',
    'asturleonese': 'ast', 'avaric': 'ava', 'avestan': 'ave', 'awadhi': 'awa',
    'aymara': 'aym', 'azerbaijani': 'aze', 'bable': 'ast', 'balinese': 'ban',
    'baluchi': 'bal', 'bambara': 'bam', 'bangla': 'ben', 'basa': 'bas',
    'bashkir': 'bak', 'basque': 'baq', 'bedawiyet': 'bej', 'beja': 'bej',
    'belarusian': 'bel', 'bemba': 'bem', 'bengali': 'ben', 'bhojpuri': 'bho',
    'bihari': 'bih', 'bikol': 'bik', 'bilin': 'byn', 'bini': 'bin',
    'bislama': 'bis', 'blin': 'byn', 'bliss': 'zbl', 'blissymbolics': 'zbl',
    'blissymbols': 'zbl', 'bosnian': 'bos', 'braj': 'bra', 'breton': 'bre',
    'buginese': 'bug', 'bulgarian': 'bul', 'buriat': 'bua', 'burmese': 'bur',
    'caddo': 'cad', 'castilian': 'spa', 'catalan': 'cat', 'cebuano': 'ceb',
    'chagatai': 'chg', 'chamorro': 'cha', 'chechen': 'che', 'cherokee': 'chr',
    'chewa': 'nya', 'cheyenne': 'chy', 'chibcha': 'chb', 'chichewa': 'nya',
    'chinese': 'chi', 'chipewyan': 'chp', 'choctaw': 'cho', 'chuang': 'zha',
    'chuukese': 'chk', 'chuvash': 'chv', 'coptic': 'cop', 'cornish': 'cor',
    'corsican': 'cos', 'cree': 'cre', 'creek': 'mus', 'croatian': 'hrv',
    'czech': 'cze', 'dakota': 'dak', 'danish': 'dan', 'dargwa': 'dar',
    'delaware': 'del', 'dhivehi': 'div', 'dimili': 'zza', 'dimli': 'zza',
    'dinka': 'din', 'divehi': 'div', 'dogri': 'doi', 'dogrib': 'dgr',
    'duala': 'dua', 'dutch': 'dut', 'dyula': 'dyu', 'dzongkha': 'dzo',
    'edo': 'bin', 'efik': 'efi', 'ekajuk': 'eka', 'elamite': 'elx',
    'english': 'eng', 'erzya': 'myv', 'esperanto': 'epo', 'estonian': 'est',
    'ewe': 'ewe', 'ewondo': 'ewo', 'fang': 'fan', 'fanti': 'fat',
    'faroese': 'fao', 'farsi': 'per', 'fijian': 'fij', 'filipino': 'fil',
    'finnish': 'fin', 'flemish': 'dut', 'fon': 'fon', 'french': 'fre',
    'friulian': 'fur', 'fulah': 'ful', 'ga': 'gaa', 'gaelic': 'gla',
    'galician': 'glg', 'ganda': 'lug', 'gayo': 'gay', 'gbaya': 'gba',
    'geez': 'gez', 'georgian': 'geo', 'german': 'ger', 'gikuyu': 'kik',
    'gilbertese': 'gil', 'gondi': 'gon', 'gorontalo': 'gor', 'gothic': 'got',
    'grebo': 'grb', 'greek': 'gre', 'greenlandic': 'kal', 'guarani': 'grn',
    'gujarati': 'guj', "gwich'in": 'gwi', 'haida': 'hai', 'haitian': 'hat',
    'hausa': 'hau', 'hawaiian': 'haw', 'hebrew': 'heb', 'herero': 'her',
    'hiligaynon': 'hil', 'hindi': 'hin', 'hittite': 'hit', 'hmong': 'hmn',
    'hungarian': 'hun', 'hupa': 'hup', 'iban': 'iba', 'icelandic': 'ice',
    'ido': 'ido', 'igbo': 'ibo', 'iloko': 'ilo', 'indonesian': 'ind',
    'ingush': 'inh', 'interlingua': 'ina', 'interlingue': 'ile', 'inuktitut': 'iku',
    'inupiaq': 'ipk', 'inupiat': 'ipk', 'irish': 'gle', 'italian': 'ita',
    'japanese': 'jpn', 'javanese': 'jav', 'jingpho': 'kac', 'kabardian': 'kbd',
    'kabyle': 'kab', 'kachin': 'kac', 'kalaallisut': 'kal', 'kalmyk': 'xal',
    'kamba': 'kam', 'kannada': 'kan', 'kanuri': 'kau', 'kapampangan': 'pam',
    'karelian': 'krl', 'kashmiri': 'kas', 'kashubian': 'csb', 'kawi': 'kaw',
    'kazakh': 'kaz', 'khasi': 'kha', 'khmer': 'khm', 'khotanese': 'kho',
    'kikuyu': 'kik', 'kimbundu': 'kmb', 'kinyarwanda': 'kin', 'kirdki': 'zza',
    'kirghiz': 'kir', 'kirmanjki': 'zza', 'kirundi': 'run', 'klingon': 'tlh',
    'komi': 'kom', 'kongo': 'kon', 'konkani': 'kok', 'korean': 'kor',
    'kosraean': 'kos', 'kpelle': 'kpe', 'kuanyama': 'kua', 'kumyk': 'kum',
    'kurdish': 'kur', 'kurukh': 'kru', 'kutenai': 'kut', 'kwanyama': 'kua',
    'kyrgyz': 'kir', 'ladino': 'lad', 'lahnda': 'lah', 'lamba': 'lam',
    'lao': 'lao', 'latin': 'lat', 'latvian': 'lav', 'leonese': 'ast',
    'letzeburgesch': 'ltz', 'lezghian': 'lez', 'limburgan': 'lim', 'limburger': 'lim',
    'limburgish': 'lim', 'lingala': 'lin', 'lithuanian': 'lit', 'lojban': 'jbo',
    'lozi': 'loz', 'luiseno': 'lui', 'lunda': 'lun', 'lushai': 'lus',
    'luxembourgish': 'ltz', 'macedonian': 'mac', 'madurese': 'mad', 'magahi': 'mag',
    'maithili': 'mai', 'makasar': 'mak', 'malagasy': 'mlg', 'malay': 'may',
    'malayalam': 'mal', 'maldivian': 'div', 'maltese': 'mlt', 'manchu': 'mnc',
    'mandar': 'mdr', 'mandingo': 'man', 'manipuri': 'mni', 'manx': 'glv',
    'maori': 'mao', 'mapuche': 'arn', 'mapudungun': 'arn', 'marathi': 'mar',
    'mari': 'chm', 'marshallese': 'mah', 'marwari': 'mwr', 'masai': 'mas',
    'mende': 'men', "mi'kmaq": 'mic', 'micmac': 'mic', 'minangkabau': 'min',
    'mirandese': 'mwl', 'mohawk': 'moh', 'moksha': 'mdf', 'moldavian': 'rum',
    'moldovan': 'rum', 'mong': 'hmn', 'mongo': 'lol', 'mongolian': 'mon',
    'montenegrin': 'cnr', 'mossi': 'mos', "n'ko": 'nqo', 'nauru': 'nau',
    'navaho': 'nav', 'navajo': 'nav', 'ndonga': 'ndo', 'neapolitan': 'nap',
    'nepali': 'nep', 'newari': 'new', 'nias': 'nia', 'niuean': 'niu',
    'nogai': 'nog', 'norwegian': 'nor', 'nuosu': 'iii', 'nyamwezi': 'nym',
    'nyanja': 'nya', 'nyankole': 'nyn', 'nyoro': 'nyo', 'nzima': 'nzi',
    'occidental': 'ile', 'occitan': 'oci', 'oirat': 'xal', 'ojibwa': 'oji',
    'oriya': 'ori', 'oromo': 'orm', 'osage': 'osa', 'ossetian': 'oss',
    'ossetic': 'oss', 'pahlavi': 'pal', 'palauan': 'pau', 'pali': 'pli',
    'pampanga': 'pam', 'pangasinan': 'pag', 'panjabi': 'pan', 'papiamento': 'pap',
    'pashto': 'pus', 'pedi': 'nso', 'persian': 'per', 'phoenician': 'phn',
    'pilipino': 'fil', 'pohnpeian': 'pon', 'polish': 'pol', 'portuguese': 'por',
    'provençal': 'oci', 'punjabi': 'pan', 'pushto': 'pus', 'quechua': 'que',
    'rajasthani': 'raj', 'rapanui': 'rap', 'rarotongan': 'rar', 'romanian': 'rum',
    'romansh': 'roh', 'romany': 'rom', 'rundi': 'run', 'russian': 'rus',
    'sakan': 'kho', 'samoan': 'smo', 'sandawe': 'sad', 'sangho': 'sag',
    'sango': 'sag', 'sanskrit': 'san', 'santali': 'sat', 'sardinian': 'srd',
    'sasak': 'sas', 'scots': 'sco', 'selkup': 'sel', 'sepedi': 'nso',
    'serbian': 'srp', 'serer': 'srr', 'sesotho': 'sot', 'shan': 'shn',
    'shona': 'sna', 'sicilian': 'scn', 'sidamo': 'sid', 'siksika': 'bla',
    'sindhi': 'snd', 'sinhala': 'sin', 'sinhalese': 'sin', 'slovak': 'slo',
    'slovenian': 'slv', 'sogdian': 'sog', 'somali': 'som', 'soninke': 'snk',
    'spanish': 'spa', 'sukuma': 'suk', 'sumerian': 'sux', 'sundanese': 'sun',
    'susu': 'sus', 'swahili': 'swa', 'swati': 'ssw', 'swedish': 'swe',
    'syriac': 'syr', 'tagalog': 'tgl', 'tahitian': 'tah', 'tajik': 'tgk',
    'tamashek': 'tmh', 'tamil': 'tam', 'tatar': 'tat', 'telugu': 'tel',
    'tereno': 'ter', 'tetum': 'tet', 'thai': 'tha', 'tibetan': 'tib',
    'tigre': 'tig', 'tigrinya': 'tir', 'timne': 'tem', 'tiv': 'tiv',
    'tlicho': 'dgr', 'tlingit': 'tli', 'tokelau': 'tkl', 'tonga': 'ton',
    'tsimshian': 'tsi', 'tsonga': 'tso', 'tswana': 'tsn', 'tumbuka': 'tum',
    'turkish': 'tur', 'turkmen': 'tuk', 'tuvalu': 'tvl', 'tuvinian': 'tyv',
    'twi': 'twi', 'udmurt': 'udm', 'ugaritic': 'uga', 'uighur': 'uig',
    'ukrainian': 'ukr', 'umbundu': 'umb', 'undetermined': 'und', 'urdu': 'urd',
    'uyghur': 'uig', 'uzbek': 'uzb', 'vai': 'vai', 'valencian': 'cat',
    'venda': 'ven', 'vietnamese': 'vie', 'volapuk': 'vol', 'volapük': 'vol',
    'votic': 'vot', 'walloon': 'wln', 'waray': 'war', 'washo': 'was',
    'welsh': 'wel', 'wolaitta': 'wal', 'wolaytta': 'wal', 'wolof': 'wol',
    'xhosa': 'xho', 'yakut': 'sah', 'yao': 'yao', 'yapese': 'yap',
    'yiddish': 'yid', 'yoruba': 'yor', 'zapotec': 'zap', 'zaza': 'zza',
    'zazaki': 'zza', 'zenaga': 'zen', 'zhuang': 'zha', 'zulu': 'zul',
    'zuni': 'zun',
}


def languageTranslate(lang, lang_from, lang_to):
  """Legacy column-to-column lookup in LANGUAGES (kept for compatibility).
  New code should use langutils.normalize() / langutils.lang_matches()."""
  for x in LANGUAGES:
    codes = x[lang_from].split(r',')
    for code in codes:
      if lang == code :
        return x[lang_to]
